      Physical Name: 
NOTE: Libref STI_WER was successfully assigned as follows: 
      Engine:        ODBC 
      Physical Name: 
NOTE: PROCEDURE SQL used (Total process time):
      real time           0.11 seconds
      cpu time            0.06 seconds
      

NOTE: No existing record for CycleID=202603. Proceeding.
NOTE: Line generated by the invoked macro "OCR_BACKFILL".
701               data _null_;          d0 = input(strip("&baseline_date."), yymmddN8.);     call symputx('sas_d0', d0, 'L');
                                                                             _________
                                                                             485
NOTE: Line generated by the invoked macro "OCR_BACKFILL".
701               d1 = input(strip("&week1_date."), yymmddN8.);       call symputx('sas_d1', d1, 'L');
                                                    _________
                                                    485
NOTE: Line generated by the invoked macro "OCR_BACKFILL".
701               d2 = input(strip("&week2_date."), yymmddN8.);       call symputx('sas_d2', d2, 'L');
                                                    _________
                                                    485
NOTE: Line generated by the invoked macro "OCR_BACKFILL".
701               d3 = input(strip("&week3_date."), yymmddN8.);       call symputx('sas_d3', d3, 'L');
                                                    _________
                                                    485

NOTE 485-185: Informat YYMMDDN was not found or could not be loaded.

NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.01 seconds
      

NOTE: baseline_date 20260316 -> SAS date 20260316 (*********).
WARNING: Apparent symbolic reference SAS_D4 not resolved.
ERROR: A character operand was found in the %EVAL function or %IF condition where a numeric operand is required. The condition was: 
       %length(&week4_date.) > 0 and &sas_d4. = . 
ERROR: The macro OCR_BACKFILL will stop executing.
