

NOTE: The infile '/tmp/tracker_json.txt' is:
      Filename=/tmp/tracker_json.txt,
      Owner Name=f8884560,Group Name=f8884560,
      Access Permission=-rw-rw-r--,
      Last Modified=07Apr2026:20:42:18,
      File Size (bytes)=137

NOTE: 2 records were read from the infile '/tmp/tracker_json.txt'.
      The minimum record length was 1.
      The maximum record length was 134.
NOTE: DATA statement used (Total process time):
      real time           0.01 seconds
      cpu time            0.01 seconds
      

WARNING: Apparent symbolic reference BASELINE_CLAIMS not resolved.
NOTE: Line generated by the macro variable "TRACKER_JSON".
625         "[{"label":"Week 3","date":"06APR2026","open":197 ,"ocr":1256864.00 ,"cumul":481 ,"closed_wk":52 ,"ocr_red":333534.00
            ____     ___             ___         ___    ________   _______________     ________         _______       ______________
            49       49              49          49     49         49                  49               49            49
                              ____
                              22
                              ____
                              200
                             _
                             156
625      ! ,"pct":0.709440 }]

NOTE 49-169: The meaning of an identifier after a quoted string might change in a future SAS release.  Inserting white space 
             between a quoted string and the succeeding identifier is recommended.

ERROR 22-322: Syntax error, expecting one of the following: a name, a quoted string, a numeric constant, arrayname, #, (, +, -, /, 
              //, ;, @, @@, OVERPRINT, _ALL_, _BLANKPAGE_, _ODS_, _PAGE_.  

ERROR 200-322: The symbol is not recognized and will be ignored.

ERROR 156-185: The decimal specification of 6 must be less than the width specification of 1.

NOTE: The SAS System stopped processing this step because of errors.
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.01 seconds
      
